=== afcowie/xseq/xml/procedure.dtd
<!-- <!ENTITY % identifier "id ID #IMPLIED"> -->
<!-- <!ATTLIST procedure %identifier;> -->

<!ELEMENT procedure (title,overview?,section*)>
<!ATTLIST procedure id ID #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title id ID #IMPLIED>

<!ELEMENT overview (#PCDATA)>
<!ATTLIST overview id ID #IMPLIED>


<!ELEMENT section (precis?,step+)>
<!ATTLIST section title CDATA #REQUIRED>
<!ATTLIST section start CDATA #IMPLIED>
<!ATTLIST section id ID #IMPLIED>

<!ELEMENT precis (#PCDATA)>
<!ATTLIST precis id ID #IMPLIED>


<!ELEMENT step (name+)>
<!ATTLIST step title CDATA #REQUIRED>
<!ATTLIST step id ID #IMPLIED>

<!ELEMENT name (task+)>
<!ATTLIST name who CDATA #REQUIRED>
<!ATTLIST name id ID #IMPLIED>

<!ELEMENT task (#PCDATA)>
<!ATTLIST task id ID #IMPLIED>
<!ATTLIST task status (done | working | problem | critical) #IMPLIED>

=== afcowie/xseq/doc/examples/simpleProcedure_v1_Example.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE procedure SYSTEM "xml/procedure.dtd">
<procedure>
	<title>Production Database Upgrade</title>
	<overview>
		In order to launch the next version of our e-commerce platform, we need
		to upgrade the schema of the core database at the heart of the
		application. We also have an outstanding requirement to upgrade the
		underlying database software, as we have had trouble with several bugs
		therein which the vendor reports fixed.
	</overview>
	<section title="Take site down" start="0515">
		<precis>
			Before taking the database offline for its upgrade, we put the site
			into maintenance mode and safely down the servers.  The start time
			is critical due to expected duration of the database schema upgrade
			scripts.
		</precis>
		<step title="Enter maintenance mode">
			<name who="Fozzie">
				<task>Put web site into maintenance mode (load balancer redirect to alternate web servers with static pages)</task>
			</name>
			<name who="Gonzo">
				<task>Activate IVR maintenance mode</task>
			</name>
		</step>
		<step title="Down services">
			<name who="Kermit">
				<task>Stop all VMs</task>
				<task>Stop GFS on database2 then database1 to prevent failover</task>
				<task>Ensure RAID filesystems still mounted</task>
			</name>
			<name who="Gonzo">
				<task>Stop Apache on web1, web2</task>
			</name>
		</step>
		<step title="Verification">
			<name who="Kermit">
				<task>Verify maintenance mode is active</task>
				<task>Verify all VMs down</task>
				<task>GO / NO-GO FOR UPGRADE</task>
			</name>
		</step>
	</section>
	<section title="Database work">
		<precis>
			Run an export of the database in order to ensure we have a good 
			backup prior to upgrading the database software and running the 
			schema change scripts. There is not much concurrent activity here,
			so those not directly involved in database
			activity will head for breakfast.
		</precis>
		<step title="Database safety">
			<name who="Beaker">
				<task>Database to single user mode</task>
				<task>Export database to secondary storage</task>
				<task>Stop database</task>
			</name>
			<name who="Gonzo">
				<task>Run out to get coffees for everyone</task>
			</name>
		</step>
		<step title="Software upgrade">
			<name who="Fozzie">
				<task>Install database software upgrade</task>
			</name>
		</step>
		<step title="Restart database">
			<name who="Beaker">
				<task>Start database</task>
			</name>
		</step>
		<step title="Preliminary database testing">
			<name who="Beaker">
				<task>Run access check scripts</task>
				<task>Run health check scripts</task>
			</name>
			<name who="Fozzie">
				<task>Restart database monitoring</task>
			</name>
		</step>
		<step title="Schema upgrade">
			<name who="Beaker">
				<task>Run scripts: database version (upgrade schema to deal with idiosyncrasies of new version of database engine)</task>
			</name>
		</step>
	</section>
	<section title="Restart site">
		<precis>
			Restore the site to normal operation.
		</precis>
		<step title="Restore services">
			<name who="Kermit">
				<task>Retart GFS on database1</task>
				<task>Retart GFS on database2</task>
				<task>Ensure RAID filesystems still mounted</task>
				<task>Start all VMs</task>
			</name>
			<name who="Gonzo">
				<task>Start Apache on web1, web2</task>
			</name>
		</step>
		<step title="Verification">
			<name who="Fozzie">
				<task>Run test suite</task>
				<task>Verify all VMs running</task>
			</name>
			<name who="Kermit">
				<task>GO / NO-GO FOR LAUNCH</task>
			</name>
		</step>
		<step title="Make site live">
			<name who="Fozzie">
				<task>Put web site into production mode (load balancer back to normal configuration)</task>
			</name>
			<name who="Gonzo">
				<task>Restore IVRs to normal operation</task>
			</name>
		</step>
	</section>
</procedure>
<!-- vim:set ts=4: -->
